{% set name = "powerlaw" %}
{% set version = "1.4.6" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "7f9d9cb39ad23af8f6cae165d47020ee8b7fa58f380c356de91ae2625577699e"

build:
  noarch: python
  number: 2
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - matplotlib-base
    - mpmath
    - numpy
    - python >={{ python_min }}
    - scipy
test:
  requires:
    - python {{ python_min }}
  imports:
    - powerlaw

about:
  home: "http://www.github.com/jeffalstott/powerlaw"
  license: "MIT"
  license_family: "MIT"
  license_file: "powerlaw.py" 
  summary: "Toolbox for testing if a probability distribution fits a power law"
  

extra:
  recipe-maintainers:
    - jaidevjoshi83
